package com.mrscanner.omega.core.fingerprint

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * Every expected value here was generated by running the actual, unmodified
 * salesforce/jarm reference functions (BSD-3-Clause) against synthetic
 * inputs — not taken from memory. See the commit that added this file for
 * the exact Python commands used. This validates everything except the raw
 * socket I/O itself (no live-network access in CI for this): cipher
 * ordering, the fuzzy-hash algorithm, and ServerHello parsing.
 */
class JarmProbeTest {

    private fun hex(bytes: ByteArray) = bytes.joinToString("") { "%02x".format(it) }
    private fun bytesOf(vararg hex: String) = hex.map { s ->
        ByteArray(s.length / 2) { i -> ((Character.digit(s[i * 2], 16) shl 4) + Character.digit(s[i * 2 + 1], 16)).toByte() }
    }

    @Test
    fun cipherMungMatchesReferenceOnOddLengthList() {
        val c5 = bytesOf("0004", "0005", "0007", "000a", "0016")
        assertEquals(listOf("0016", "000a", "0007", "0005", "0004"), JarmProbe.cipherMung(c5, "REVERSE").map { hex(it) })
        assertEquals(listOf("0007", "0005", "0004"), JarmProbe.cipherMung(c5, "TOP_HALF").map { hex(it) })
        assertEquals(listOf("000a", "0016"), JarmProbe.cipherMung(c5, "BOTTOM_HALF").map { hex(it) })
        assertEquals(listOf("0007", "000a", "0005", "0016", "0004"), JarmProbe.cipherMung(c5, "MIDDLE_OUT").map { hex(it) })
    }

    @Test
    fun cipherMungMatchesReferenceOnEvenLengthList() {
        val c10 = (0..9).map { "%04x".format(it) }.let { bytesOf(*it.toTypedArray()) }
        assertEquals(listOf("0004", "0003", "0002", "0001", "0000"), JarmProbe.cipherMung(c10, "TOP_HALF").map { hex(it) })
        assertEquals(listOf("0005", "0006", "0007", "0008", "0009"), JarmProbe.cipherMung(c10, "BOTTOM_HALF").map { hex(it) })
        assertEquals(
            listOf("0005", "0004", "0006", "0003", "0007", "0002", "0008", "0001", "0009", "0000"),
            JarmProbe.cipherMung(c10, "MIDDLE_OUT").map { hex(it) }
        )
        assertEquals((9 downTo 0).map { "%04x".format(it) }, JarmProbe.cipherMung(c10, "REVERSE").map { hex(it) })
    }

    @Test
    fun cipherBytesMatchesReferenceIndex() {
        assertEquals("01", JarmProbe.cipherBytes("0004"))
        assertEquals("45", JarmProbe.cipherBytes("1305"))
        assertEquals("00", JarmProbe.cipherBytes(""))
        assertEquals("46", JarmProbe.cipherBytes("ffff")) // unknown cipher -> index past the end of the table
    }

    @Test
    fun versionByteMatchesReference() {
        assertEquals("d", JarmProbe.versionByte("0303"))
        assertEquals("0", JarmProbe.versionByte(""))
        assertEquals("e", JarmProbe.versionByte("0304"))
    }

    @Test
    fun jarmHashMatchesReferenceForAKnownRawString() {
        val raw = "c02f|0303|h2|c02f-000a-0016,c030|0303|h2|c030-000b,|||,|||,|||,|||,|||,|||,|||,|||"
        assertEquals("29d2ad0000000000000000000000005a38b20a38045896dbe03a194e67a281", JarmProbe.jarmHash(raw))
    }

    @Test
    fun jarmHashOfAllTimeoutsIs62Zeros() {
        val allBlank = List(10) { "|||" }.joinToString(",")
        assertEquals("0".repeat(62), JarmProbe.jarmHash(allBlank))
    }

    @Test
    fun readPacketParsesASyntheticServerHello() {
        // Built with a struct-packed ServerHello: cipher c02f, version 0303, ALPN "h2", extensions [0010, ff01]
        val recordHex = "160303005a0200005603030000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000c02f00000e001000050003026832ff01000100"
        val data = bytesOf(recordHex).first()
        assertEquals("c02f|0303|h2|0010-ff01", JarmProbe.readPacket(data))
    }

    @Test
    fun readPacketReturnsBlankOnEmptyOrMalformedInput() {
        assertEquals("|||", JarmProbe.readPacket(ByteArray(0)))
        assertEquals("|||", JarmProbe.readPacket(byteArrayOf(21, 0, 0, 0, 0, 0))) // alert record, not handshake
        assertEquals("|||", JarmProbe.readPacket(byteArrayOf(1, 2, 3))) // too short to even inspect
    }

    @Test
    fun cipherListsHaveNoTypos() {
        // 69 and 64 entries respectively, per the actual reference source — a single misplaced/duplicated
        // entry here (which happened once during development — see the fix commit) silently produces a
        // plausible-looking but wrong ClientHello, so pin the exact counts and the first few bytes.
        assertEquals(69, JarmProbe.CIPHERS_ALL.size)
        assertEquals(64, JarmProbe.CIPHERS_NO13.size)
        assertEquals(listOf("0016", "0033", "0067"), JarmProbe.CIPHERS_ALL.take(3).map { hex(it) })
    }
}
